<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<section class="home-hero" aria-labelledby="welcome-title">
    <div class="hero-copy"><p class="eyebrow"><span class="eyebrow-dot"></span> The refill desk · <?= esc(date('l, F j', strtotime($today))) ?></p><h1 id="welcome-title">A good refill starts <em>before the doors open.</em></h1><p>Keep the dispensers ready, containers circulating, and customer orders on track. Here is the work scheduled for today.</p><div class="hero-actions"><a class="button button-dark" href="#todays-work">See today’s work <span aria-hidden="true">↓</span></a><a class="button button-outline" href="<?= site_url('tasks') ?>">View full schedule <span aria-hidden="true">↗</span></a></div></div>
    <div class="hero-visual"><img src="<?= base_url('assets/images/refill-station.svg') ?>" width="760" height="640" alt="Illustration of reusable bottles below soap and cleaning product refill dispensers"><div class="visual-stamp"><span>THE REFILL ROUTINE</span><strong>Bring back.<br>Fill up.<br>Use again.</strong></div></div>
</section>
<section class="shop-stats" aria-label="Shop record counts"><div><span>01 / DAILY WORK</span><strong><?= count($tasks) ?></strong><p>tasks scheduled today</p></div><div><span>02 / COMMUNITY</span><strong><?= esc($customerCount) ?></strong><p>customer records</p></div><div><span>03 / SHOP TEAM</span><strong><?= esc($userCount) ?></strong><p>staff records</p></div></section>
<section class="today-section" id="todays-work" aria-labelledby="today-title"><div class="section-top"><div><p class="eyebrow">Today's refill routine</p><h2 id="today-title">At the refill bar<span class="heading-period">.</span></h2><p>Only tasks dated <?= esc(date('F j, Y', strtotime($today))) ?> appear here.</p></div><a class="inline-link" href="<?= site_url('tasks') ?>">All scheduled tasks <span aria-hidden="true">↗</span></a></div>
<?php if ($tasks === []): ?><div class="empty-state"><strong>No tasks scheduled today.</strong><p>See the full schedule for work on other dates.</p></div><?php else: ?>
<?php $completedToday = count(array_filter($tasks, static fn (array $task): bool => $task['status'] === 'completed')); ?>
<div class="daily-progress"><div><span>SHOP RHYTHM</span><strong><?= $completedToday ?> of <?= count($tasks) ?> tasks complete</strong></div><progress value="<?= $completedToday ?>" max="<?= count($tasks) ?>"><?= $completedToday ?> of <?= count($tasks) ?></progress></div>
<div class="task-list"><?php foreach ($tasks as $index => $task): ?><article class="task-item"><span class="task-number"><?= esc(str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT)) ?></span><div class="task-copy"><h3><?= esc($task['title']) ?></h3><span>Refill shop · <?= esc(date('M j', strtotime($task['task_date']))) ?></span></div><span class="status status-<?= esc(str_replace(' ', '-', $task['status'])) ?>"><?= esc(ucwords($task['status'])) ?></span></article><?php endforeach ?></div><?php endif ?></section>
<section class="refill-cycle" aria-labelledby="cycle-title"><div class="cycle-heading"><p class="eyebrow">The idea behind the shop</p><h2 id="cycle-title">A little less new, <em>every time.</em></h2><p>The refill concept is built around a simple repeatable routine.</p></div><div class="cycle-steps"><div class="cycle-step"><span class="cycle-icon" aria-hidden="true"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 8h14v7l5 6v19H12V21l5-6V8Zm-2 0h18M17 29h14"/></svg></span><span class="cycle-number">01 / BRING</span><h3>Bring a container</h3><p>Start with a bottle or jar ready to use again.</p></div><div class="cycle-step"><span class="cycle-icon" aria-hidden="true"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2"><path d="M24 5c8 12 13 19 13 26a13 13 0 0 1-26 0c0-7 5-14 13-26Z"/><path d="M17 30a7 7 0 0 0 7 7"/></svg></span><span class="cycle-number">02 / REFILL</span><h3>Take what you need</h3><p>Refill household essentials at the counter.</p></div><div class="cycle-step"><span class="cycle-icon" aria-hidden="true"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2"><path d="M40 20a16 16 0 1 0 1 9M40 9v11H29"/></svg></span><span class="cycle-number">03 / REPEAT</span><h3>Come back again</h3><p>Keep the container in use for the next visit.</p></div></div></section>
<section class="shop-paths" aria-label="Explore shop records"><a href="<?= site_url('customers') ?>"><span class="path-icon" aria-hidden="true">C</span><span><small>THE COMMUNITY</small><strong>Customer records</strong><em>Keep every refill relationship in view.</em></span><b aria-hidden="true">↗</b></a><a href="<?= site_url('users') ?>"><span class="path-icon" aria-hidden="true">S</span><span><small>THE TEAM</small><strong>Staff directory</strong><em>The people behind the counter.</em></span><b aria-hidden="true">↗</b></a></section>
<?= $this->endSection() ?>
